### ISSUE TITLE
TcpSink doesn't have a finalizer

### ISSUE THREAD

**Issue by leotsarev** [serilog-contrib/Serilog.Sinks.Network#24]
We sometimes see in our production that we have a lot of `TcpSocketWriter`s and small number of `TcpSink`s. VM can go out of sockets, effectively preventing our application from writing logs or make outbound connections. Seems thats somewhere we have a lot of `TcpSink`s born and die w/o `Dispose`. 
We understand that's probably bug in our code, and we are working on it, but I think that `TcpSink` will benefit from having finalizer and implementing old-style dispose pattern, disposing `TcpSocketWriter` on finalization. What do you think? If yes, we can provide a PR.

P.S. @pauldambra I wonder if the project is maintained still or it's recommended  to move to other sinks? We are happy to contribute and fix bugs — but only there is project has active mantainer and there are other users :-)

**Comment by pauldambra** [comment]
More than happy to receive a PR!

I'm not working with .Net any more so I'm not actively maintaining this but have seen other folk are using it... the dotNet standard upgrade was entirely not my work for example

It's a while since I've thought about TCP in detail - do we need to worry about performance if we're actively disposing of Sinks? Don't want to stand the cost of initialisation if it's a problem.... Not a leading question just a thought. Maybe we need a test that starts and uses many sinks wrapped in a timeout so we can be sure that we're not adding startup cost? (Also happy to be told that's not how TCP works and to not worry about it :D)

**Comment by sflusov** [comment]
Hi @leotsarev, @pauldambra,

I've prepared [pull request](https://github.com/pauldambra/Serilog.Sinks.Network/pull/25) which should solve this problem.
Could you review it?

**Comment by pauldambra** [comment]
very old PR with no tests
