### ISSUE TITLE
TCPSink tls mode don't allow to pass certificate for SslStream

### ISSUE THREAD

**Issue by fundlg** [serilog-contrib/Serilog.Sinks.Network#26]
Hello. Using your lib i found that we can't pass certificates to SslStream constructor. Is there some another way to use certificates or should it be implemented? I need your help

https://github.com/pauldambra/Serilog.Sinks.Network/blob/8fcb0cefae6c5c54536716b7bb254fb0328226ad/Serilog.Sinks.Network/Sinks/TCP/TCPSocketWriter.cs#L84-L86

**Comment by pauldambra** [comment]
sorry, I missed this when you raised the request.

It's a very reasonable request and would be a candidate for an overload on the TCPSink factory methods... 

Would need details on how the server was set up in order to write a test to cover the functionality. 

I'll close it now as I'm assuming you don't still have the need three years on :'(
